# Build Commands
[build]
base = ""
publish = "build"
command = "npm run build"

# HTTP Response Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
